# Generated by Django 4.0.4 on 2022-05-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=5)),
                ('passwd', models.CharField(blank=True, max_length=100)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gates.gates')),
            ],
        ),
    ]
