# Generated by Django 4.0.4 on 2022-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=5)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
    ]
