# Generated by Django 4.0.4 on 2022-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zkdevice',
            name='passwd',
            field=models.CharField(default='', max_length=100),
        ),
    ]
