# Generated by Django 4.0.4 on 2022-06-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gates',
            new_name='Gate',
        ),
    ]
