# Generated by Django 4.0.4 on 2022-05-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0002_alter_zkdevice_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zkdevice',
            name='passwd',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
