# Generated by Django 4.0.4 on 2022-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0002_rename_gates_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
