# Generated by Django 4.0.4 on 2022-06-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0003_gate_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=15)),
                ('pin', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('Gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gates.gate')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gates.zkdevice')),
            ],
        ),
    ]
