# Generated by Django 4.0.4 on 2022-06-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0004_loghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loghistory',
            old_name='Gate',
            new_name='gate',
        ),
        migrations.RenameField(
            model_name='loghistory',
            old_name='ip',
            new_name='zk_device',
        ),
    ]
