# Generated by Django 4.0.4 on 2022-06-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0005_rename_gate_loghistory_gate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaildMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Member', 'Member')], max_length=10)),
                ('card', models.CharField(max_length=15)),
                ('pin', models.CharField(max_length=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('zk_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gates.zkdevice')),
            ],
        ),
        migrations.AlterField(
            model_name='loghistory',
            name='pin',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='FaildTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.CharField(max_length=8)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gates.faildmember')),
            ],
        ),
    ]
