# Generated by Django 4.0.4 on 2022-06-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0006_faildmember_alter_loghistory_pin_faildtimezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faildmember',
            name='end_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='faildmember',
            name='start_date',
            field=models.CharField(max_length=8),
        ),
    ]
