# Generated by Django 4.0.4 on 2022-06-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0007_alter_faildmember_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faildtimezone',
            old_name='date',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='faildmember',
            name='end_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='faildmember',
            name='start_date',
            field=models.CharField(max_length=10),
        ),
    ]
